// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconMdi:arrowLeft': typeof import('~icons/mdi/arrow-left')['default']
    'IconMdi:facebook': typeof import('~icons/mdi/facebook')['default']
    'IconMdi:instagram': typeof import('~icons/mdi/instagram')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
