export default [
  {
    id: 1,
    title: 'Petit Déjeuner',
    image: '/assets/category/petit-déjeuner.jpg',
  },
  { id: 2, title: 'Coffee', image: '/assets/category/coffee.jpg' },
  { id: 3, title: 'Thé', image: '/assets/category/thé.jpg' },
  { id: 4, title: 'Coffee In', image: '/assets/category/coffee-in.jpg' },
  { id: 5, title: 'Glace', image: '/assets/category/glace.jpg' },
  { id: 6, title: 'Juice', image: '/assets/category/juice.jpg' },
  { id: 7, title: 'Crêpe', image: '/assets/category/crêpe.jpg' },
  { id: 8, title: 'Fast food', image: '/assets/category/fast-food.jpg' },
  { id: 9, title: 'So kids', image: '/assets/category/kids.jpg' },
  { id: 10, title: 'Pizza', image: '/assets/category/pizza.jpg' },
  { id: 11, title: 'Entrée', image: '/assets/category/entree.jpg' },
  { id: 12, title: 'Pasta', image: '/assets/category/pasta.jpg' },
  { id: 13, title: 'Plats', image: '/assets/category/plats.jpg' },
  { id: 14, title: 'Sea food', image: '/assets/category/sea-food.jpg' },
  { id: 15, title: 'Dessert', image: '/assets/category/dessert.jpg' },
  { id: 16, title: 'Drinks', image: '/assets/category/drinks.jpg' },
  { id: 17, title: 'Chicha', image: '/assets/category/chicha.jpg' },
]
