export default [
  {
    Coffee: [
      {
        id: 1,
        title: 'Chocolat au lait',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/chocolat-au-lait.jpg',
      },
      {
        id: 2,
        title: 'Nescafé au lait',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/Nescafe-au-lait.jpg',
      },
      {
        id: 3,
        title: 'Express',
        description: '',
        price: '4.000DT',
        image: '/assets/coffee/Express.jpeg',
      },
      {
        id: 4,
        title: 'Café américain',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/Café-américain.jpg',
      },
      {
        id: 5,
        title: 'Capucin',
        description: '',
        price: '5.800DT',
        image: '/assets/coffee/Capucin.jpg',
      },
      {
        id: 6,
        title: 'Direct',
        description: '',
        price: '6.500DT',
        image: '/assets/coffee/Direct.jpg',
      },
      {
        id: 7,
        title: 'Cappuccin spécial',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/Cappuccin-spécial.jpg',
      },
      {
        id: 8,
        title: 'Direct spécial',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Direct-spécial.jpg',
      },
      {
        id: 9,
        title: 'Cappuccino',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Cappuccino.jpg',
      },
      {
        id: 10,
        title: 'Cappuccino spécial',
        description: '',
        price: '10.000DT',
        image: '/assets/coffee/Cappuccino-spécial.webp',
      },
    ],
    'Italien Cofee': [
      {
        id: 1,
        title: 'Expresso',
        description: '',
        price: '6.000DT',
        image: '/assets/coffee/Italian-coffee-expresso.jpg',
      },
      {
        id: 2,
        title: 'Spécial Expresso',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/Italian-coffee-special-expresso.jpg',
      },
      {
        id: 3,
        title: 'Expresso macchiato',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/Expresso-macchiato.jpeg',
      },
      {
        id: 4,
        title: 'Spécial expresso macchiato',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Spécial-expresso-macchiato.png',
      },
      {
        id: 5,
        title: 'Direct',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Italian-coffe-direct.jpg',
      },
      {
        id: 6,
        title: 'Spécial direct',
        description: '',
        price: '9.000DT',
        image: '/assets/coffee/Italian-coffe-direct-special.jpg',
      },
      {
        id: 7,
        title: 'Cappuccino',
        description: '',
        price: '10.000DT',
        image: '/assets/coffee/Italian-coffee-Cappuccino.jpg',
      },
      {
        id: 8,
        title: 'Spécial cappuccino',
        description: '',
        price: '12.000DT',
        image: '/assets/coffee/italian-Cappuccino-special.jpg',
      },
    ],
    'Cafe Turk': [
      {
        id: 1,
        title: 'Café Turc',
        description: 'Café turc préparé dans le sable chaud',
        price: '10.000DT',
        image: '/assets/coffee/CAFÉ-TURC.jpg',
      },
    ],
  },
  {
    Thé: [
      {
        id: 1,
        title: 'Thé à la menthe',
        description: '',
        price: '5.000DT',
        image: '/assets/thé/The-a-la-menthe.jpg',
      },
      {
        id: 2,
        title: 'Thé Lipton',
        description: 'eau minérale',
        price: '7.000DT',
        image: '/assets/thé/The-Lipton.jpg',
      },
      {
        id: 3,
        title: 'Thé aux amandes',
        description: '',
        price: '9.000DT',
        image: '/assets/thé/The-aux-amandes.jpg',
      },
      {
        id: 4,
        title: 'Thé aux pignons',
        description: '',
        price: '12.000DT',
        image: '/assets/thé/The-aux-pignons.jpg',
      },
      {
        id: 5,
        title: 'Thé Baklawa',
        description: 'Fruit sec',
        price: '14.000DT',
        image: '/assets/thé/The-Baklawa.jpg',
      },
    ],
  },
  {
    'Coffee In': [
      {
        id: 1,
        title: 'Café glacé',
        description: 'Express, glaçon, caramel',
        price: '8.000DT',
        image: '/assets/COFFEE-IN/Café-glacé.jpg',
      },
      {
        id: 2,
        title: 'Café latte caramel',
        description: 'express, mousse, sauce caramel',
        price: '8.000DT',
        image: '/assets/COFFEE-IN/Café-latte-caramel.jpg',
      },
      {
        id: 3,
        title: 'Choco latte',
        description: 'Chocolat chaud, lait, mousse, chantilly',
        price: '8.000DT',
        image: '/assets/COFFEE-IN/Choco-latte.jpg',
      },
      {
        id: 4,
        title: 'Choco café noisette',
        description:
          'Chocolat chaud, express, boule de glace, mousse lait, chantilly, arôme fruit sec, noisette',
        price: '9.500DT',
        image: '/assets/COFFEE-IN/Choco-café-noisette.jpg',
      },
      {
        id: 5,
        title: 'Choco café pistache',
        description:
          'Chocolat chaud, express, boule de glace, mousse lait, chantilly, arôme fruit sec, pistache',
        price: '9.500DT',
        image: '/assets/COFFEE-IN/Choco-café-pistache.jpg',
      },
      {
        id: 6,
        title: 'Choco banane',
        description: 'Chocolat chaud, banane, chantilly',
        price: '9.500DT',
        image: '/assets/COFFEE-IN/Choco-banane.jpg',
      },
      {
        id: 7,
        title: 'Café glacé liégeois',
        description: 'Express froide, boule de glace, caramel, chantilly',
        price: '10.000DT',
        image: '/assets/COFFEE-IN/cafe-liégeois.jpg',
      },
      {
        id: 8,
        title: 'Café frappé',
        description: 'Express, Boule de glace, vanille, glaçon',
        price: '10.000DT',
        image: '/assets/COFFEE-IN/Café-frappé.jpg',
      },
      {
        id: 9,
        title: 'Chocolat chaud',
        description: '',
        price: '10.000DT',
        image: '/assets/COFFEE-IN/chocolat_chaud_1.jpg',
      },
      {
        id: 10,
        title: 'Frappuccino',
        description: 'Express, boule de glace, vanille, glaçon, chantilly',
        price: '12.000DT',
        image: '/assets/COFFEE-IN/Frappuccino.jpg',
      },
      {
        id: 11,
        title: 'Choco glacé liégeois',
        description: 'Chocolat glacé, boule de glace, caramel, chantilly',
        price: '12.000DT',
        image: '/assets/COFFEE-IN/Choco-glacé-liégeois.jpg',
      },
      {
        id: 12,
        title: 'Choco chaud viennois',
        description: 'Chocolat chaud, boule de glace, caramel, chantilly',
        price: '12.000DT',
        image: '/assets/COFFEE-IN/Choco-chaud-viennois.jpg',
      },
      {
        id: 13,
        title: 'Chocolat chaud aux fruit sec',
        description: '',
        price: '14.000DT',
        image: '/assets/COFFEE-IN/Chocolat-chaud-aux-fruit-sec.jpg',
      },
    ],
  },
  {
    Glace: [
      {
        id: 1,
        title: 'Glaces',
        description: '2 boules au choix',
        price: '9.000DT',
        image: '/assets/glace/glace-2-boule.jpg',
      },
      {
        id: 2,
        title: 'Glaces',
        description: '3 boules au choix',
        price: '10.000DT',
        image: '/assets/glace/Glace-3-boule.avif',
      },
      {
        id: 3,
        title: 'Glaces',
        description: '2 boules fruit secs',
        price: '12.000DT',
        image: '/assets/glace/Glace-2-boule-fruits-sec.jpg',
      },
      {
        id: 4,
        title: 'Glaces',
        description: '3 boules fruit secs',
        price: '14.000DT',
        image: '/assets/glace/glace-3-boule-fruits-sec.jpg',
      },
      {
        id: 5,
        title: 'Banana split',
        description: '3 boules au choix',
        price: '15.000DT',
        image: '/assets/glace/banana-split-3-boule-aux-choix.jpg',
      },
      {
        id: 6,
        title: 'Banana split',
        description: '3 boules aux fruit secs',
        price: '16.000DT',
        image: '/assets/glace/banana-split-3-boule-fruit-sec.jpg',
      },
    ],
  },
  {
    Milkshake: [
      {
        id: 1,
        title: 'Milk shake kinder',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/milkshake/Milk-shake-kinder.jpg',
      },
      {
        id: 2,
        title: 'Milk shake oreo',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/milkshake/Milk-shake-oreo.jpg',
      },
      {
        id: 3,
        title: 'Milk shake spéculoos',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/milkshake/Milk-shake-spéculoos.jpg',
      },
      {
        id: 4,
        title: 'Milk shake Nutella',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/milkshake/Milk-shake-Nutella.jpg',
      },
      {
        id: 5,
        title: 'Milk shake banane',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/milkshake/Milk-shake-banane.jpg',
      },
      {
        id: 6,
        title: 'Milk shake aux fruits',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/milkshake/Milk-shake-aux-fruits.jpg',
      },
    ],
    Cocktail: [
      {
        id: 1,
        title: 'Jus banane datte',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-banane-datte.jpg',
      },
      {
        id: 2,
        title: 'Jus orange banane',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-orange-banane.jpg',
      },
      {
        id: 3,
        title: 'Jus fraise banane',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-fraise-banane.jpg',
      },
      {
        id: 4,
        title: 'Jus fraise citron',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-fraise-citron.jpg',
      },
      {
        id: 5,
        title: 'Jus kiwi fraise',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-kiwi-fraise.jpg',
      },
      {
        id: 6,
        title: 'Jus kiwi banane',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-kiwi-banane.jpg',
      },
      {
        id: 7,
        title: 'Cocktail',
        description: '4 étages',
        price: '15.000DT',
        image: '/assets/juice/COCKTAIL/Cocktail.jpg',
      },
      {
        id: 8,
        title: 'Cocktail The 21',
        description: 'Banane datte , fruits secs, chantilly',
        price: '18.000DT',
        image: '/assets/juice/COCKTAIL/Cocktail-The-21.jpg',
      },
    ],
    'Mixte Jus': [
      {
        id: 1,
        title: 'Blue planet',
        description: 'sprite, citron , noix de coco, glaçon, arôme blue',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Blue-planet-cocktail.jpg',
      },
      {
        id: 2,
        title: 'Malibu',
        description: 'kiwi, citronnade, menthe vert, glaçon',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Malibu-jus.jpg',
      },
      {
        id: 3,
        title: 'Blue drink',
        description: 'Schweppes agrume, limonade, colorant bleu, menthe vert',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Blue-drink.jpg',
      },
      {
        id: 4,
        title: 'Cindrella',
        description: 'Orange, ananas, goutte limonade',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Cindrella.jpg',
      },
      {
        id: 5,
        title: 'Hawaï',
        description: 'Limonade, jus ananas, sirop, grenadine',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/jus-Hawai.jpg',
      },
      {
        id: 6,
        title: 'Tequila Blanche',
        description: 'Schweppes tonic, Limonade, Tranche citron',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Tequila-Blanche.jpg',
      },
      {
        id: 7,
        title: 'Tequila menthe',
        description: 'Boga, Limonade, Tranche citron, menthe vert',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Tequila-menthe.jpg',
      },
      {
        id: 8,
        title: 'Indien',
        description: 'Orangina, grenadine, arôme, glaçon',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Indien.jpg',
      },
    ],
    Mojito: [
      {
        id: 1,
        title: 'Mojito virgin',
        description: 'Sprite, menthe, citron',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Mojito-virgin.jpg',
      },
      {
        id: 2,
        title: 'Kiwi Mojito',
        description: 'Kiwi, menthe vert, arôme, glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Kiwi-Mojito.jpg',
      },
      {
        id: 3,
        title: 'Mojito pina colada',
        description: 'Menthe vert , citron, ananas',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Mojito-pina-colada.jpg',
      },
      {
        id: 4,
        title: 'Apple mojito',
        description: 'Pomme , menthe vert, arôme , glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Apple-mojito.jpeg',
      },
      {
        id: 5,
        title: 'Fraise mojito',
        description: 'Fraise, Menthe vert, arôme glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Fraise-mojito.jpg',
      },
      {
        id: 6,
        title: 'Mojito coca',
        description: 'Citron, menthe vert arôme, glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/coca-mojito.jpg',
      },
      {
        id: 7,
        title: 'Melon mojito',
        description: 'Melon, menthe vert, arôme, glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Mojito-melon.png',
      },
      {
        id: 8,
        title: 'Mojito énergisant',
        description: 'Red-bull, menthe vert, arôme, glaçon',
        price: '16.000DT',
        image: '/assets/juice/MOJITO/Mojito-energisant.jpg',
      },
    ],
    Juice: [
      {
        id: 1,
        title: 'Citronnade',
        description: '',
        price: '10.000DT',
        image: '/assets/juice/Juice/Citronnade.jpg',
      },
      {
        id: 2,
        title: 'Jus d’orange',
        description: '',
        price: '10.000DT',
        image: '/assets/juice/Juice/Jus-dorange.jpg',
      },
      {
        id: 3,
        title: 'Jus de fraise frais',
        description: '',
        price: '11.000DT',
        image: '/assets/juice/Juice/Jus-de-fraise-frais.jpg',
      },
      {
        id: 4,
        title: 'Citronnade à la menthe frais ',
        description: '',
        price: '11.000DT',
        image: '/assets/juice/Juice/Citronnade-a-la-menthe.jpg',
      },
      {
        id: 5,
        title: 'Lait de poule',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Lait-de-poule.jpg',
      },
      {
        id: 6,
        title: 'Citronnade + boule de glace ',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Citronnade-boule-de-glace.jpg',
      },
      {
        id: 7,
        title: 'Jus de kiwi ',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Jus-de-kiwi.jpg',
      },
      {
        id: 8,
        title: 'Jus de mangue frais',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Jus-de-mangue.jpg',
      },
      {
        id: 9,
        title: 'Jus ananas ',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Jus-ananas.jpg',
      },
      {
        id: 10,
        title: 'Citronnade aux amandes',
        description: '',
        price: '14.000DT',
        image: '/assets/juice/Juice/Citronnade-aux-amandes.JPG',
      },
      {
        id: 11,
        title: 'Jus de Fraise spécial',
        description: '',
        price: '14.000DT',
        image: '/assets/juice/Juice/Jus-de-Fraise-special.jpg',
      },
      {
        id: 12,
        title: 'Lait de poule spécial ',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/Juice/Lait-de-poule-special.jpg',
      },
    ],
    Smoothie: [
      {
        id: 1,
        title: 'Smoothie aux choix',
        description: 'kiwi au fraise au banane',
        price: '14.000DT',
        image: '/assets/juice/smoothie/Smoothie-aux-choix.jpg',
      },
      {
        id: 2,
        title: 'Smoothie énergisant',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/smoothie/Smoothie-energisant.jpg',
      },
    ],
  },
  {
    'Crêpe Chocolat': [
      {
        id: 1,
        title: 'Crêpe',
        description: 'Chocolat',
        price: '8.000DT',
        image: '/assets/Crepe/smoothie/Crepe-fruits-secs.jpg',
      },
      {
        id: 2,
        title: 'Crêpe fruits secs',
        description: '',
        price: '10.000DT',
        image: '/assets/Crepe/smoothie/Crepe-fruits-secs.jpeg',
      },
      {
        id: 3,
        title: 'Crêpe banane',
        description: '',
        price: '10.000DT',
        image: '/assets/Crepe/smoothie/Crepe-banane.jpg',
      },
      {
        id: 4,
        title: 'Crêpe Oreo',
        description: '',
        price: '12.000DT',
        image: '/assets/Crepe/smoothie/Crepe-Oreo.jpeg',
      },
      {
        id: 5,
        title: 'Crêpe banane fruits secs',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/smoothie/Crepe-banane-fruits-secs.webp',
      },
    ],
    // 'Bubble Waffle': [
    //   {
    //     id: 1,
    //     title: 'Smoothie',
    //     description: 'kiwi',
    //     price: '14.000DT',
    //     image: '/assets/Crepe/smoothie/Smoothie',
    //   },
    // ],
    // Gaufre: [
    //   {
    //     id: 1,
    //     title: 'Smoothie',
    //     description: 'kiwi',
    //     price: '14.000DT',
    //     image: '/assets/Crepe/smoothie/Smoothie',
    //   },
    // ],
    // 'Pain Cake': [
    //   {
    //     id: 1,
    //     title: 'Smoothie',
    //     description: 'kiwi',
    //     price: '14.000DT',
    //     image: '/assets/Crepe/smoothie/Smoothie',
    //   },
    // ],
  },
]
