export default [
  {
    Coffee: [
      {
        id: 1,
        title: 'Chocolat au lait',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/chocolat-au-lait.jpg',
      },
      {
        id: 2,
        title: 'Nescafé au lait',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/Nescafe-au-lait.jpg',
      },
      {
        id: 3,
        title: 'Express',
        description: '',
        price: '4.000DT',
        image: '/assets/coffee/Express.jpeg',
      },
      {
        id: 4,
        title: 'Café américain',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/Café-américain.jpg',
      },
      {
        id: 5,
        title: 'Capucin',
        description: '',
        price: '5.800DT',
        image: '/assets/coffee/Capucin.jpg',
      },
      {
        id: 6,
        title: 'Direct',
        description: '',
        price: '6.500DT',
        image: '/assets/coffee/Direct.jpg',
      },
      {
        id: 7,
        title: 'Cappuccin spécial',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/Cappuccin-spécial.jpg',
      },
      {
        id: 8,
        title: 'Direct spécial',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Direct-spécial.jpg',
      },
      {
        id: 9,
        title: 'Cappuccino',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Cappuccino.jpg',
      },
      {
        id: 10,
        title: 'Cappuccino spécial',
        description: '',
        price: '10.000DT',
        image: '/assets/coffee/Cappuccino-spécial.webp',
      },
    ],
    'Italien Cofee': [
      {
        id: 1,
        title: 'Expresso',
        description: '',
        price: '6.000DT',
        image: '/assets/coffee/Italian-coffee-expresso.jpg',
      },
      {
        id: 2,
        title: 'Spécial Expresso',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/Italian-coffee-special-expresso.jpg',
      },
      {
        id: 3,
        title: 'Expresso macchiato',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/Expresso-macchiato.jpeg',
      },
      {
        id: 4,
        title: 'Spécial expresso macchiato',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Spécial-expresso-macchiato.png',
      },
      {
        id: 5,
        title: 'Direct',
        description: '',
        price: '8.000DT',
        image: '/assets/coffee/Italian-coffe-direct.jpg',
      },
      {
        id: 6,
        title: 'Spécial direct',
        description: '',
        price: '9.000DT',
        image: '/assets/coffee/Italian-coffe-direct-special.jpg',
      },
      {
        id: 7,
        title: 'Cappuccino',
        description: '',
        price: '10.000DT',
        image: '/assets/coffee/Italian-coffee-Cappuccino.jpg',
      },
      {
        id: 8,
        title: 'Spécial cappuccino',
        description: '',
        price: '12.000DT',
        image: '/assets/coffee/italian-Cappuccino-special.jpg',
      },
    ],
    'Cafe Turk': [
      {
        id: 1,
        title: 'Café Turc',
        description: 'Café turc préparé dans le sable chaud',
        price: '10.000DT',
        image: '/assets/coffee/CAFÉ-TURC.jpg',
      },
    ],
    'Arômes & Suppléments': [
      {
        id: 1,
        title: 'ARÔMES',
        description: 'Caramel, noissette, vanille, cookies, Chantilly, Nestlé',
        price: '4.000DT',
        image: '/assets/coffee/aromas.jpg',
      },
      {
        id: 1,
        title: 'Amandes',
        description: '',
        price: '5.000DT',
        image: '/assets/coffee/Amandes.jpg',
      },
      {
        id: 1,
        title: 'Pignons',
        description: '',
        price: '7.000DT',
        image: '/assets/coffee/pignon.webp',
      },
    ],
  },
  {
    Thé: [
      {
        id: 1,
        title: 'Thé à la menthe',
        description: '',
        price: '5.000DT',
        image: '/assets/thé/The-a-la-menthe.jpg',
      },
      {
        id: 2,
        title: 'Thé Infusion',
        description: 'eau minérale',
        price: '7.000DT',
        image: '/assets/thé/The-Lipton.jpg',
      },
      {
        id: 3,
        title: 'Thé aux amandes',
        description: '',
        price: '9.000DT',
        image: '/assets/thé/The-aux-amandes.jpg',
      },
      {
        id: 4,
        title: 'Thé aux pignons',
        description: '',
        price: '12.000DT',
        image: '/assets/thé/The-aux-pignons.jpg',
      },
      {
        id: 5,
        title: 'Thé Baklawa',
        description: 'Fruit sec',
        price: '14.000DT',
        image: '/assets/thé/The-Baklawa.jpg',
      },
    ],
  },
  {
    'Coffee In': [
      {
        id: 1,
        title: 'Café glacé',
        description: 'Express, glaçon, caramel',
        price: '8.000DT',
        image: '/assets/COFFEE-IN/Café-glacé.jpg',
      },
      {
        id: 2,
        title: 'Café latte caramel',
        description: 'express, mousse, sauce caramel',
        price: '8.000DT',
        image: '/assets/COFFEE-IN/Café-latte-caramel.jpg',
      },
      {
        id: 3,
        title: 'Choco latte',
        description: 'Chocolat chaud, lait, mousse, chantilly',
        price: '8.000DT',
        image: '/assets/COFFEE-IN/Choco-latte.jpg',
      },
      {
        id: 4,
        title: 'Choco café noisette',
        description:
          'Chocolat chaud, express, boule de glace, mousse lait, chantilly, arôme fruit sec, noisette',
        price: '9.500DT',
        image: '/assets/COFFEE-IN/Choco-café-noisette.jpg',
      },
      {
        id: 5,
        title: 'Choco café pistache',
        description:
          'Chocolat chaud, express, boule de glace, mousse lait, chantilly, arôme fruit sec, pistache',
        price: '9.500DT',
        image: '/assets/COFFEE-IN/Choco-café-pistache.jpg',
      },
      {
        id: 6,
        title: 'Choco banane',
        description: 'Chocolat chaud, banane, chantilly',
        price: '9.500DT',
        image: '/assets/COFFEE-IN/Choco-banane.jpg',
      },
      {
        id: 7,
        title: 'Café glacé liégeois',
        description: 'Express froide, boule de glace, caramel, chantilly',
        price: '10.000DT',
        image: '/assets/COFFEE-IN/cafe-liégeois.jpg',
      },
      {
        id: 8,
        title: 'Café frappé',
        description: 'Express, Boule de glace, vanille, glaçon',
        price: '10.000DT',
        image: '/assets/COFFEE-IN/Café-frappé.jpg',
      },
      {
        id: 9,
        title: 'Chocolat chaud',
        description: '',
        price: '10.000DT',
        image: '/assets/COFFEE-IN/chocolat_chaud_1.jpg',
      },
      {
        id: 10,
        title: 'Frappuccino',
        description: 'Express, boule de glace, vanille, glaçon, chantilly',
        price: '12.000DT',
        image: '/assets/COFFEE-IN/Frappuccino.jpg',
      },
      {
        id: 11,
        title: 'Choco glacé liégeois',
        description: 'Chocolat glacé, boule de glace, caramel, chantilly',
        price: '12.000DT',
        image: '/assets/COFFEE-IN/Choco-glacé-liégeois.jpg',
      },
      {
        id: 12,
        title: 'Choco chaud viennois',
        description: 'Chocolat chaud, boule de glace, caramel, chantilly',
        price: '12.000DT',
        image: '/assets/COFFEE-IN/Choco-chaud-viennois.jpg',
      },
      {
        id: 13,
        title: 'Chocolat chaud aux fruit sec',
        description: '',
        price: '14.000DT',
        image: '/assets/COFFEE-IN/Chocolat-chaud-aux-fruit-sec.jpg',
      },
    ],
  },
  {
    Glace: [
      {
        id: 1,
        title: 'Glaces',
        description: '2 boules au choix',
        price: '9.000DT',
        image: '/assets/glace/glace-2-boule.jpg',
      },
      {
        id: 2,
        title: 'Glaces',
        description: '3 boules au choix',
        price: '10.000DT',
        image: '/assets/glace/Glace-3-boule.avif',
      },
      {
        id: 3,
        title: 'Glaces',
        description: '2 boules fruit secs',
        price: '12.000DT',
        image: '/assets/glace/Glace-2-boule-fruits-sec.jpg',
      },
      {
        id: 4,
        title: 'Glaces',
        description: '3 boules fruit secs',
        price: '14.000DT',
        image: '/assets/glace/glace-3-boule-fruits-sec.jpg',
      },
      {
        id: 5,
        title: 'Banana split',
        description: '3 boules au choix',
        price: '15.000DT',
        image: '/assets/glace/banana-split-3-boule-aux-choix.jpg',
      },
      {
        id: 6,
        title: 'Banana split',
        description: '3 boules aux fruit secs',
        price: '16.000DT',
        image: '/assets/glace/banana-split-3-boule-fruit-sec.jpg',
      },
    ],
  },
  {
    Milkshake: [
      {
        id: 1,
        title: 'Milk shake kinder',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/milkshake/Milk-shake-kinder.jpg',
      },
      {
        id: 2,
        title: 'Milk shake oreo',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/milkshake/Milk-shake-oreo.jpg',
      },
      {
        id: 3,
        title: 'Milk shake spéculoos',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/milkshake/Milk-shake-spéculoos.jpg',
      },
      {
        id: 4,
        title: 'Milk shake Nutella',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/milkshake/Milk-shake-Nutella.jpg',
      },
      {
        id: 5,
        title: 'Milk shake banane',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/milkshake/Milk-shake-banane.jpg',
      },
      {
        id: 6,
        title: 'Milk shake aux fruits',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/milkshake/Milk-shake-aux-fruits.jpg',
      },
    ],
    Cocktail: [
      {
        id: 1,
        title: 'Jus banane datte',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-banane-datte.jpg',
      },
      {
        id: 2,
        title: 'Jus orange banane',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-orange-banane.jpg',
      },
      {
        id: 3,
        title: 'Jus fraise banane',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-fraise-banane.jpg',
      },
      {
        id: 4,
        title: 'Jus fraise citron',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-fraise-citron.jpg',
      },
      {
        id: 5,
        title: 'Jus kiwi fraise',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-kiwi-fraise.jpg',
      },
      {
        id: 6,
        title: 'Jus kiwi banane',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/COCKTAIL/Jus-kiwi-banane.jpg',
      },
      {
        id: 7,
        title: 'Cocktail',
        description: '4 étages',
        price: '15.000DT',
        image: '/assets/juice/COCKTAIL/Cocktail.jpg',
      },
      {
        id: 8,
        title: 'Cocktail The 21',
        description: 'Banane datte , fruits secs, chantilly',
        price: '18.000DT',
        image: '/assets/juice/COCKTAIL/Cocktail-The-21.jpg',
      },
    ],
    'Mixte Jus': [
      {
        id: 1,
        title: 'Blue planet',
        description: 'sprite, citron , noix de coco, glaçon, arôme blue',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Blue-planet-cocktail.jpg',
      },
      {
        id: 2,
        title: 'Malibu',
        description: 'kiwi, citronnade, menthe vert, glaçon',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Malibu-jus.jpg',
      },
      {
        id: 3,
        title: 'Blue drink',
        description: 'Schweppes agrume, limonade, colorant bleu, menthe vert',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Blue-drink.jpg',
      },
      {
        id: 4,
        title: 'Cindrella',
        description: 'Orange, ananas, goutte limonade',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Cindrella.jpg',
      },
      {
        id: 5,
        title: 'Hawaï',
        description: 'Limonade, jus ananas, sirop, grenadine',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/jus-Hawai.jpg',
      },
      {
        id: 6,
        title: 'Tequila Blanche',
        description: 'Schweppes tonic, Limonade, Tranche citron',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Tequila-Blanche.jpg',
      },
      {
        id: 7,
        title: 'Tequila menthe',
        description: 'Boga, Limonade, Tranche citron, menthe vert',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Tequila-menthe.jpg',
      },
      {
        id: 8,
        title: 'Indien',
        description: 'Orangina, grenadine, arôme, glaçon',
        price: '14.000DT',
        image: '/assets/juice/MIXTE-JUS/Indien.jpg',
      },
    ],
    Mojito: [
      {
        id: 1,
        title: 'Mojito virgin',
        description: 'Sprite, menthe, citron',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Mojito-virgin.jpg',
      },
      {
        id: 2,
        title: 'Kiwi Mojito',
        description: 'Kiwi, menthe vert, arôme, glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Kiwi-Mojito.jpg',
      },
      {
        id: 3,
        title: 'Mojito pina colada',
        description: 'Menthe vert , citron, ananas',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Mojito-pina-colada.jpg',
      },
      {
        id: 4,
        title: 'Apple mojito',
        description: 'Pomme , menthe vert, arôme , glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Apple-mojito.jpg',
      },
      {
        id: 5,
        title: 'Fraise mojito',
        description: 'Fraise, Menthe vert, arôme glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Fraise-mojito.jpg',
      },
      {
        id: 6,
        title: 'Mojito coca',
        description: 'Citron, menthe vert arôme, glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/coca-mojito.jpg',
      },
      {
        id: 7,
        title: 'Melon mojito',
        description: 'Melon, menthe vert, arôme, glaçon',
        price: '12.000DT',
        image: '/assets/juice/MOJITO/Mojito-melon.png',
      },
      {
        id: 8,
        title: 'Mojito énergisant',
        description: 'Red-bull, menthe vert, arôme, glaçon',
        price: '16.000DT',
        image: '/assets/juice/MOJITO/Mojito-energisant.jpg',
      },
    ],
    Juice: [
      {
        id: 1,
        title: 'Citronnade',
        description: '',
        price: '10.000DT',
        image: '/assets/juice/Juice/Citronnade.jpg',
      },
      {
        id: 2,
        title: 'Jus d’orange',
        description: '',
        price: '10.000DT',
        image: '/assets/juice/Juice/Jus-dorange.jpg',
      },
      {
        id: 3,
        title: 'Jus de fraise frais',
        description: '',
        price: '11.000DT',
        image: '/assets/juice/Juice/Jus-de-fraise-frais.jpg',
      },
      {
        id: 4,
        title: 'Citronnade à la menthe frais ',
        description: '',
        price: '11.000DT',
        image: '/assets/juice/Juice/Citronnade-a-la-menthe.jpg',
      },
      {
        id: 5,
        title: 'Lait de poule',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Lait-de-poule.jpg',
      },
      {
        id: 6,
        title: 'Citronnade + boule de glace ',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Citronnade-boule-de-glace.jpg',
      },
      {
        id: 7,
        title: 'Jus de kiwi ',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Jus-de-kiwi.jpg',
      },
      {
        id: 8,
        title: 'Jus de mangue frais',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Jus-de-mangue.jpg',
      },
      {
        id: 9,
        title: 'Jus ananas ',
        description: '',
        price: '12.000DT',
        image: '/assets/juice/Juice/Jus-ananas.jpg',
      },
      {
        id: 10,
        title: 'Citronnade aux amandes',
        description: '',
        price: '14.000DT',
        image: '/assets/juice/Juice/Citronnade-aux-amandes.JPG',
      },
      {
        id: 11,
        title: 'Jus de Fraise spécial',
        description: '',
        price: '14.000DT',
        image: '/assets/juice/Juice/Jus-de-Fraise-special.jpg',
      },
      {
        id: 12,
        title: 'Lait de poule spécial ',
        description: '',
        price: '16.000DT',
        image: '/assets/juice/Juice/Lait-de-poule-special.jpg',
      },
    ],
    Smoothie: [
      {
        id: 1,
        title: 'Smoothie aux choix',
        description: 'kiwi au fraise au banane',
        price: '14.000DT',
        image: '/assets/juice/smoothie/Smoothie-aux-choix.jpg',
      },
      {
        id: 2,
        title: 'Smoothie énergisant',
        description: '',
        price: '18.000DT',
        image: '/assets/juice/smoothie/Smoothie-energisant.jpg',
      },
    ],
  },
  {
    'Crêpe Chocolat': [
      {
        id: 1,
        title: 'Crêpe',
        description: 'Chocolat',
        price: '8.000DT',
        image: '/assets/Crepe/crepe-normal-chocolat/Crepe-fruits-secs.jpg',
      },
      {
        id: 2,
        title: 'Crêpe fruits secs',
        description: '',
        price: '10.000DT',
        image: '/assets/Crepe/crepe-normal-chocolat/Crepe-fruits-secs.jpeg',
      },
      {
        id: 3,
        title: 'Crêpe banane',
        description: '',
        price: '10.000DT',
        image: '/assets/Crepe/crepe-normal-chocolat/Crepe-banane.jpg',
      },
      {
        id: 4,
        title: 'Crêpe Oreo',
        description: '',
        price: '12.000DT',
        image: '/assets/Crepe/crepe-normal-chocolat/Crepe-Oreo.jpeg',
      },
      {
        id: 5,
        title: 'Crêpe banane fruits secs',
        description: '',
        price: '14.000DT',
        image:
          '/assets/Crepe/crepe-normal-chocolat/Crepe-banane-fruits-secs.webp',
      },
    ],
    'Crêpe Nutella': [
      {
        id: 1,
        title: 'Crêpe Nutella',
        description: '',
        price: '12.000DT',
        image: '/assets/Crepe/crepe-nutella/CrêpeNutella.jpg',
      },
      {
        id: 2,
        title: 'Crêpe fruits secs',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/crepe-nutella/Crêpefruitssecs.jpeg',
      },
      {
        id: 3,
        title: 'Crêpe banane',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/crepe-nutella/Crêpebanane.jpg',
      },
      {
        id: 4,
        title: 'Crêpe Oreo',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/crepe-nutella/CrêpeOreo.jpeg',
      },
      {
        id: 5,
        title: 'Crêpe banane fruits secs',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/crepe-nutella/Crêpebananefruitssecs.jpg',
      },
      {
        id: 6,
        title: 'Crêpe spéculoos',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/crepe-nutella/crepes-tout-speculoos.png',
      },
      {
        id: 7,
        title: 'Crêpe pistacho',
        description: 'beurre de pistache, Nutella',
        price: '16.000DT',
        image: '/assets/Crepe/crepe-nutella/Crêpepistacho.jpg',
      },
      {
        id: 8,
        title: 'Supréme Nutella',
        description: 'beurre de noisette, fruits secs, ferrero rocher',
        price: '16.000DT',
        image: '/assets/Crepe/crepe-nutella/SuprémeNutella.jpg',
      },
      {
        id: 9,
        title: 'Snickers',
        description: 'beurre de caramel, beurre de cacahuétes, snickers',
        price: '16.000DT',
        image: '/assets/Crepe/crepe-nutella/crepeSnickers.webp',
      },
      {
        id: 10,
        title: 'Crêpe Makis',
        description: 'banane , nuttela, pistache',
        price: '18.000DT',
        image: '/assets/Crepe/crepe-nutella/Crêpe-Makis.png',
      },
    ],
    'Crêpe Salée': [
      {
        id: 1,
        title: 'Crêpe Thon Fromage',
        description: '',
        price: '12.000DT',
        image: '/assets/Crepe/crepe-sale/CrêpeThonFromage.jpg',
      },
      {
        id: 2,
        title: 'Crêpe Jambon Fromage',
        description: '',
        price: '12.000DT',
        image: '/assets/Crepe/crepe-sale/CrêpeJambonFromage.webp',
      },
      {
        id: 3,
        title: 'Crêpe thon oeuf fromage',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/crepe-sale/Crêpethonoeuffromage.jpg',
      },
      {
        id: 4,
        title: 'Crêpe poulet',
        description: 'sauce blanche, fromage, poulet',
        price: '16.000DT',
        image: '/assets/Crepe/crepe-sale/Crêpepoulet.jpg',
      },
    ],
    'Bubble Waffle': [
      {
        id: 1,
        title: 'Nutella',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/bubblewaffle/bubblewafflebanan.jpg',
      },
      {
        id: 2,
        title: 'Nutella fruits',
        description: '',
        price: '18.000DT',
        image: '/assets/Crepe/bubblewaffle/Nutellafruits.jpg',
      },
      {
        id: 3,
        title: 'Nutella fruits secs',
        description: '',
        price: '18.000DT',
        image: '/assets/Crepe/bubblewaffle/bubblewafflefruitssecs.jpg',
      },
    ],
    'Gaufre Chocolat': [
      {
        id: 1,
        title: 'Gaufre',
        description: '',
        price: '10.000DT',
        image: '/assets/Crepe/gauffre/Gaufre.jpg',
      },
      {
        id: 2,
        title: 'Gaufre fruits secs',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/gauffre/Gaufre-fruits-secs.jpg',
      },
      {
        id: 3,
        title: 'Gaufre banane',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/gauffre/Gaufre-banane.jpg',
      },
      {
        id: 4,
        title: 'Gaufre banane fruits secs',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/gauffre/Gaufre-banane-fruits-secs.jpg',
      },
    ],
    'Gaufre Nutella': [
      {
        id: 1,
        title: 'Gaufre Nutella',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/gauffre-nutella/GaufreNutella.jpg',
      },
      {
        id: 2,
        title: 'Gaufre fruits secs',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/gauffre-nutella/Gaufrefruitssecs.jpg',
      },
      {
        id: 3,
        title: 'Gaufre banane',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/gauffre-nutella/Gaufrebanane.jpg',
      },
      {
        id: 4,
        title: 'Gaufre banane fruits secs',
        description: '',
        price: '18.000DT',
        image: '/assets/Crepe/gauffre-nutella/Gaufrebananfruitsec.jpg',
      },
      {
        id: 5,
        title: 'Gaufre The 21',
        description: 'Fruits, glaces, chantilly, fruits secs',
        price: '20.000DT',
        image: '/assets/Crepe/gauffre-nutella/GaufreThe21.jpg',
      },
    ],
    'Pain Cake Chocolat': [
      {
        id: 1,
        title: 'Pancake chocolat',
        description: '',
        price: '11.000DT',
        image: '/assets/Crepe/Pancake/PANCAKEchocolat/PancakeChocolat.jpg',
      },
      {
        id: 2,
        title: 'Pancake chocolat banane',
        description: '',
        price: '14.000DT',
        image:
          '/assets/Crepe/Pancake/PANCAKEchocolat/Pancakechocolatbanane.jpg',
      },
      {
        id: 3,
        title: 'Pancake chocolat fruits secs',
        description: '',
        price: '14.000DT',
        image:
          '/assets/Crepe/Pancake/PANCAKEchocolat/Pancakechocolatfruitssecs.jpg',
      },
      {
        id: 4,
        title: 'Pancake chocolat spécial',
        description: 'banane, fruits secs',
        price: '15.000DT',
        image:
          '/assets/Crepe/Pancake/PANCAKEchocolat/Pancakechocolatspécial.jpg',
      },
    ],
    'Pain Cake Nutella': [
      {
        id: 1,
        title: 'Pancake Nutella',
        description: '',
        price: '14.000DT',
        image: '/assets/Crepe/Pancake/PANCAKEnutella/PancakeNutella.jpg',
      },
      {
        id: 1,
        title: 'Pancake Nutella fruits secs',
        description: '',
        price: '16.000DT',
        image:
          '/assets/Crepe/Pancake/PANCAKEnutella/PancakeNutellafruitssecs.webp',
      },
      {
        id: 1,
        title: 'Pancake Nutella banane',
        description: '',
        price: '16.000DT',
        image: '/assets/Crepe/Pancake/PANCAKEnutella/PancakeNutellabanane.jpg',
      },
      {
        id: 1,
        title: 'Pancake Nutella spécial',
        description: 'banane, fruits secs',
        price: '18.000DT',
        image:
          '/assets/Crepe/Pancake/PANCAKEnutella/PancakeNutellaspécial.jpeg',
      },
    ],
  },
  {
    Panini: [
      {
        id: 1,
        title: 'Panini thon fromage',
        description: '',
        price: '10.000DT',
        image: '/assets/Fast-food/Panini/Paninithonfromage.jpg',
      },
      {
        id: 2,
        title: 'Panini jambon fromage',
        description: '',
        price: '10.000DT',
        image: '/assets/Fast-food/Panini/Paninijambonfromage.jpg',
      },
    ],
    Sandwich: [
      {
        id: 1,
        title: 'Libanais',
        description: '',
        price: '12.000DT',
        image: '/assets/Fast-food/Sandwich/Libanais.jpg',
      },
      {
        id: 2,
        title: 'Libanais Kabeb',
        description: '',
        price: '14.000DT',
        image: '/assets/Fast-food/Sandwich/LibanaisKabeb.jpeg',
      },
      {
        id: 3,
        title: 'Baguette farcie',
        description: '',
        price: '16.000DT',
        image: '/assets/Fast-food/Sandwich/Baguettefarcie.jpeg',
      },
    ],
    'Family Food': [
      {
        id: 1,
        title: '4 PERSONNES',
        description: "2 BURGER'S + 2 SANDWICHS LIBANAIS + SODA (1L)",
        price: '45.000DT',
        image: '/assets/Fast-food/Familyfood.jpg',
      },
    ],
    Omelette: [
      {
        id: 1,
        title: 'Omelette',
        description: 'Thon, fromage, frite',
        price: '14.000DT',
        image: '/assets/Fast-food/omlette.webp',
      },
    ],
    Burger: [
      {
        id: 1,
        title: 'Burger Poulet Singele',
        description: '',
        price: '14.000DT',
        image: '/assets/Fast-food/burger/Burgerpoulet.jpg',
      },
      {
        id: 2,
        title: 'Burger Poulet Double',
        description: '',
        price: '16.000DT',
        image: '/assets/Fast-food/burger/Burgerpoulet.jpg',
      },
      {
        id: 3,
        title: 'Burger Viande Singele',
        description: '',
        price: '14.000DT',
        image: '/assets/Fast-food/burger/burgerviande.jpg',
      },
      {
        id: 4,
        title: 'Burger Viande Double',
        description: '',
        price: '16.000DT',
        image: '/assets/Fast-food/burger/burgerviande.jpg',
      },
    ],
    SUPPLEMENT: [
      {
        id: 1,
        title: 'Gruyér',
        description: '',
        price: '5.000DT',
        image: '/assets/Fast-food/SUPPLEMENT/SUPPLEMENTgruyer.jpg',
      },
      {
        id: 2,
        title: 'Thon',
        description: '',
        price: '5.000DT',
        image: '/assets/Fast-food/SUPPLEMENT/SUPPLEMENTthon.png',
      },
      {
        id: 3,
        title: 'Jambon',
        description: '',
        price: '3.000DT',
        image: '/assets/Fast-food/SUPPLEMENT/SUPPLEMENTjambon.png',
      },
      {
        id: 4,
        title: 'Oeuf',
        description: '',
        price: '3.000DT',
        image: '/assets/Fast-food/SUPPLEMENT/SUPPLEMENToeuf.jpg',
      },
      {
        id: 5,
        title: 'Bacon',
        description: '',
        price: '5.000DT',
        image: '/assets/Fast-food/SUPPLEMENT/supplementbacon.jpg',
      },
      {
        id: 6,
        title: 'Frites',
        description: '',
        price: '5.000DT',
        image: '/assets/Fast-food/SUPPLEMENT/supplementfrites.jpg',
      },
    ],
  },
  {
    'MENU KIDS': [
      {
        id: 1,
        title: 'KIDS 1',
        description: 'NUGGETS + FRITE + SODA',
        price: '14.000DT',
        image: '/assets/Menu-kids/Kids1.jpg',
      },
      {
        id: 2,
        title: 'KIDS 2',
        description: 'MINI PIZZA + FRITE + SODA',
        price: '14.000DT',
        image: '/assets/Menu-kids/Kid2.jpg',
      },
      {
        id: 3,
        title: 'KIDS FOOD 1 (2 ENFANTS)',
        description: 'CHEESBURGER+ NUGGETS + 2 FRITES + 2 SODAS',
        price: '26.000DT',
        image: '/assets/Menu-kids/kidsfood1.jpg',
      },
      {
        id: 4,
        title: 'KIDS FOOD 2 (2 ENFANTS)',
        description: '2 CHEESBURGER+2 FRITES + 2 SODAS',
        price: '28.000DT',
        image: '/assets/Menu-kids/KIDSFOOD2.jpg',
      },
    ],
  },
  {
    Pizza: [
      {
        id: 1,
        title: 'Pizza Végétarienne',
        description: 'Fromage, légume',
        price: '16.000DT',
        image: '/assets/pizza/Pizza-Végétarienne.jpg',
      },
      {
        id: 2,
        title: 'Pizza Neptune',
        description: 'sauce tomate, thon, fromage, olive',
        price: '18.000DT',
        image: '/assets/pizza/Pizza-Neptune.jpeg',
      },
      {
        id: 3,
        title: 'Pizza Pepperoni',
        description: 'sauce tomate,fromage, pepperoni',
        price: '18.000DT',
        image: '/assets/pizza/Pizza-Pepperoni.jpg',
      },
      {
        id: 4,
        title: 'Pizza 4 Saisons',
        description: 'sauce tomate,fromage, jambon, olive, champignon',
        price: '21.000DT',
        image: '/assets/pizza/Pizza-4-Saisons.webp',
      },
      {
        id: 5,
        title: 'Pizza 4 fromages',
        description: 'créme fraiche, mozzarella, gruyére, roquefort, sicilien',
        price: '21.000DT',
        image: '/assets/pizza/Pizza-4-fromages.jpg',
      },
      {
        id: 6,
        title: 'Pizza Burrata',
        description: 'sauce tomate, tomates cerise, burrata',
        price: '24.000DT',
        image: '/assets/pizza/Pizza-Burrata.jpg',
      },
      {
        id: 7,
        title: 'Pizza Fruit de mer',
        description: '',
        price: '26.000DT',
        image: '/assets/pizza/Pizza-Fruit-de-mer.jpg',
      },
      {
        id: 8,
        title: 'Pizza 4 fromages',
        description:
          'Double pâte, sauce tomate, mozzarella, fromage fondu, champignon, viande hachée',
        price: '29.000DT',
        image: '/assets/pizza/Pizza-4-fromages29.000DT.jpg',
      },
    ],
  },
  {
    Entrée: [
      {
        id: 1,
        title: 'Salade Mechouia',
        description: '',
        price: '10.000DT',
        image: '/assets/Entree/entree/SaladeMechouia.jpg',
      },
      {
        id: 2,
        title: 'Salade tunisienne',
        description: '',
        price: '10.000DT',
        image: '/assets/Entree/entree/Saladetunisienne.jpeg',
      },
      {
        id: 3,
        title: 'Assortiment de saldes',
        description: '',
        price: '22.000DT',
        image: '/assets/Entree/entree/Assortimentdesaldes.jpg',
      },
      {
        id: 4,
        title: 'Brick thon',
        description: '',
        price: '8.000DT',
        image: '/assets/Entree/entree/Brickthon.jpeg',
      },
      {
        id: 5,
        title: 'Brick Chevrette',
        description: '',
        price: '10.000DT',
        image: '/assets/Entree/entree/BrickChevrette.jpg',
      },
      {
        id: 6,
        title: 'Calamar pannée',
        description: '',
        price: '20.000DT',
        image: '/assets/Entree/entree/Calamarpannée.webp',
      },
      {
        id: 7,
        title: 'Calamar sauté',
        description: '',
        price: '20.000DT',
        image: '/assets/Entree/entree/Calamarsauté.jpg',
      },
      {
        id: 8,
        title: 'Chevrette pannée',
        description: '',
        price: '25.000DT',
        image: '/assets/Entree/entree/Chevrettepannée.webp',
      },
    ],
    Salade: [
      {
        id: 1,
        title: 'Salade à la mozzarella',
        description: '',
        price: '14.000DT',
        image: '/assets/Entree/salade/Salademozzarella.jpg',
      },
      {
        id: 2,
        title: 'Salade césar',
        description: '',
        price: '18.000DT',
        image: '/assets/Entree/salade/Saladecésar.webp',
      },
      {
        id: 3,
        title: 'Salade fruits de mer',
        description: '',
        price: '28.000DT',
        image: '/assets/Entree/salade/Saladefruitsdemer.jpg',
      },
      {
        id: 4,
        title: 'Salade buraata',
        description: '',
        price: '20.000DT',
        image: '/assets/Entree/salade/Saladeburaata.jpg',
      },
      {
        id: 5,
        title: 'Salade niçoise',
        description: '',
        price: '18.000DT',
        image: '/assets/Entree/salade/Saladeniçoise.webp',
      },
    ],
  },
  {
    Pasta: [
      {
        id: 1,
        title: 'Carbonara',
        description: 'Penne - spaghetti',
        price: '22.000DT',
        image: '/assets/pasta/pastaCarbonara.jpg',
      },
      {
        id: 2,
        title: 'Puttanesca',
        description: 'Penne - spaghetti',
        price: '22.000DT',
        image: '/assets/pasta/pastaPuttanesca.jpg',
      },
      {
        id: 3,
        title: 'Bolognaise',
        description: 'Penne - spaghetti',
        price: '22.000DT',
        image: '/assets/pasta/pastaBolognaise.jpg',
      },
      {
        id: 4,
        title: 'Lasagne Bolognaise',
        description: '',
        price: '22.000DT',
        image: '/assets/pasta/LasagneBolognaise.jpg',
      },
      {
        id: 5,
        title: 'Penne Chevrettes',
        description: '',
        price: '28.000DT',
        image: '/assets/pasta/PenneChevrettes.jpg',
      },
      {
        id: 6,
        title: 'Penne sauce Blanche',
        description: 'saumon, chevrettes',
        price: '30.000DT',
        image: '/assets/pasta/PennesauceBlanche.jpg',
      },
      {
        id: 7,
        title: 'Fruits de mer',
        description: 'Penne - spaghetti ',
        price: '32.000DT',
        image: '/assets/pasta/pastaFruitsdemer.jpg',
      },
    ],
    'Ravioli Frais': [
      {
        id: 1,
        title: '4 Fromage',
        description: '',
        price: '24.000DT',
        image: '/assets/pasta/RAVIOLI4frommage.webp',
      },
      {
        id: 2,
        title: 'Viande Hachée',
        description: '',
        price: '26.000DT',
        image: '/assets/pasta/ravioliviandehaché.jpg',
      },
    ],
  },
  {
    Plat: [
      {
        id: 1,
        title: 'Escalope grillé',
        description: '',
        price: '20.000DT',
        image: '/assets/Plat/platEscalopegrillé.jpg',
      },
      {
        id: 2,
        title: 'Escalope panée',
        description: '',
        price: '20.000DT',
        image: '/assets/Plat/platEscalopepanée.webp',
      },
      {
        id: 3,
        title: 'Escalope à la créme',
        description: '',
        price: '25.000DT',
        image: '/assets/Plat/platEscalopeàlacréme.jpg',
      },
      {
        id: 4,
        title: 'Cordon bleu',
        description: '',
        price: '25.000DT',
        image: '/assets/Plat/Cordonbleu.webp',
      },
      {
        id: 5,
        title: 'Chich taouk',
        description: '',
        price: '25.000DT',
        image: '/assets/Plat/Chichtaouk.jpg',
      },
      {
        id: 6,
        title: 'Kebeb',
        description: '',
        price: '25.000DT',
        image: '/assets/Plat/Kebeb.jpg',
      },
      {
        id: 7,
        title: 'Kebeb royale',
        description: 'pistacho PISTACHE, FROMAGE',
        price: '30.000DT',
        image: '/assets/Plat/Kebebroyalepistacho.webp',
      },
      {
        id: 8,
        title: 'Filet grillé',
        description: '',
        price: '39.000DT',
        image: '/assets/Plat/Filetgrillé.jpg',
      },
      {
        id: 9,
        title: 'Filet à la créme',
        description: '',
        price: '40.000DT',
        image: '/assets/Plat/Filetàlacréme.jpg',
      },
      {
        id: 10,
        title: 'Grillade mixte',
        description: '',
        price: '42.000DT',
        image: '/assets/Plat/Grillademixte.jpg',
      },
    ],
  },
  {
    'Sea Food': [
      {
        id: 1,
        title: 'Filet de poisson',
        description: '',
        price: '25.000DT',
        image: '/assets/Seafood/Filetdepoisson.jpg',
      },
      {
        id: 2,
        title: 'Chevrette sauté à l’ail',
        description: '',
        price: '30.000DT',
        image: '/assets/Seafood/Chevrettesautéàlail.webp',
      },
      {
        id: 3,
        title: 'Loup farci',
        description: '',
        price: '30.000DT',
        image: '/assets/Seafood/Loupfarci.jpg',
      },
      {
        id: 4,
        title: 'Paella',
        description: '',
        price: '35.000DT',
        image: '/assets/Seafood/Paella.jpg',
      },
      {
        id: 5,
        title: 'Crevette Royale',
        description: 'sauté au pané',
        price: '40.000DT',
        image: '/assets/Seafood/CrevetteRoyale.jpeg',
      },
      {
        id: 6,
        title: 'Grillade Fruit de Mer',
        description: '',
        price: '52.000DT',
        image: '/assets/Seafood/GrilladeFruitdeMer.jpg',
      },

      {
        id: 7,
        title: 'TRÉSOR THE 21',
        description: '',
        price: '119.000DT',
        image: '/assets/Seafood/tresore21.jpg',
      },
    ],
  },
  {
    Dessert: [
      {
        id: 1,
        title: 'Tiramisu',
        description: '',
        price: '12.000DT',
        image: '/assets/DESSERT/Tiramisu.jpg',
      },
      {
        id: 2,
        title: 'Cheesecake',
        description: '',
        price: '12.000DT',
        image: '/assets/DESSERT/Cheesecake.jpg',
      },
      {
        id: 3,
        title: 'Fondant au chocolat',
        description: '',
        price: '12.000DT',
        image: '/assets/DESSERT/Fondantauxchocolat.jpg',
      },
      {
        id: 4,
        title: 'Jwejem',
        description: '',
        price: '12.000DT',
        image: '/assets/DESSERT/Jwejem.png',
      },
      {
        id: 5,
        title: 'Gâteau',
        description: '',
        price: '15.000DT',
        image: '/assets/DESSERT/Gâteau.jpg',
      },
      {
        id: 6,
        title: 'Coupe fruit & glaces',
        description: '',
        price: '17.000DT',
        image: '/assets/DESSERT/Coupefruit.jpeg',
      },
      {
        id: 7,
        title: 'Assiette de desserts',
        description: '2 personnes',
        price: '15.000DT',
        image: '/assets/DESSERT/Assiettededesserts.jpg',
      },
    ],
  },
  {
    Drinks: [
      {
        id: 1,
        title: 'Soda',
        description: '',
        price: '5.000DT',
        image: '/assets/drinks/Soda.jpg',
      },
      {
        id: 2,
        title: 'Eau minérale',
        description: '0.5 L',
        price: '2.000DT',
        image: '/assets/drinks/Eauminérale.jpg',
      },
      {
        id: 3,
        title: 'Eau plate',
        description: '1L',
        price: '5.000DT',
        image: '/assets/drinks/Eauplate.jpg',
      },
      {
        id: 4,
        title: 'Eau gazéifiée',
        description: '',
        price: '5.000DT',
        image: '/assets/drinks/Eaugazéifiée.jpg',
      },
      {
        id: 5,
        title: 'Shark',
        description: '',
        price: '12.000DT',
        image: '/assets/drinks/Shark.jpg',
      },
      {
        id: 6,
        title: 'Redbull',
        description: '',
        price: '12.000DT',
        image: '/assets/drinks/Redbull.jpg',
      },
      {
        id: 7,
        title: 'Arôme',
        description: '',
        price: '2.500DT',
        image: '/assets/drinks/Arôme.jpeg',
      },
    ],
  },
  {
    Chicha: [
      {
        id: 1,
        title: 'CHICHA TONY GUM',
        description: 'POMME , MENTHE, RAISIN',
        price: '15.000DT',
        image: '/assets/Chicha/tchichatonygum.jpg',
      },
      {
        id: 2,
        title: 'CHICHA HOOKAH',
        description: 'POMME , MENTHE, RAISIN LOVE, SHEIKHMAMY, CHEWING GUM',
        price: '20.000DT',
        image: '/assets/Chicha/CHICHAHOOKAH.jpg',
      },
      {
        id: 3,
        title: 'CHICHA WOOKAH',
        description: 'ASSIETTE FRUIT',
        price: '25.000DT',
        image: '/assets/Chicha/CHICHAWOOKAH.jpg',
      },
      {
        id: 4,
        title: 'JEBED',
        description: '',
        price: '4.000DT',
        image: '/assets/Chicha/JEBED.jpg',
      },
      {
        id: 5,
        title: 'CHARBON',
        description: '',
        price: '5.000DT',
        image: '/assets/Chicha/CHARBON.jpg',
      },
    ],
  },
]
